### ISSUE TITLE
Question:  Will you refact it with faye?

### ISSUE THREAD

**Issue by ZhangHanDong** [andrewhavens/mad_chatter#22]
Will you refact it with faye?

**Comment by andrewhavens** [comment]
Thanks for the question. Yes, the plan is to refactor Mad Chatter to use Faye so that it can be hosted on standard cloud hosting servers like Heroku. Unfortunately, I have not had much time to do so, but I plan on finishing this refactoring within the next month.

**Comment by ZhangHanDong** [comment]
Awesome!
